[theme]
theme = "slick"
[theme.overrides]
warning_bg = "#ED7D3A"
separator = ""

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_w:40) |"

[[block]]
block = "pacman"
interval = 3600
format_up_to_date = ""
aur_command = "paru -Qua"
critical_updates_regex = "linux"
[[block.click]]
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs/ | rofi -dmenu"

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
interval = 3
format = " $icon $utilization "

[[block]]
block = "time"

[[block]]
block = "backlight"
cycle = [100, 75, 50, 25]

[[block]]
block = "sound"
driver = "pulseaudio"
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "battery"
missing_format = ""
warning = 20
critical = 10

# [[block]]
# block = "keyboard_layout"
# driver = "kbddbus"
# [block.mappings]
# "English (US)" = "en"
# "Russian (N/A)" = "ru"
# [[block.click]]
# button = "left"
# cmd = "xkb-switch -n"
# update = true
