# format = " $directory$python$git_branch$cmd_duration\n $character"
format = "$all"

[directory.substitutions]
"~" = " "

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[cmd_duration]
format = "[祥$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
