#!/usr/bin/env fish

if test -n "$WAYLAND_DISPLAY"
    wlsunset -s 20:00 -S 6:00 -t 3000
else
    # the thing in parentheses is needed to determine location via gps and pass it to redshift
    redshift -l (curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | awk 'OFS=":" {print $3,$5}' | tr -d ',}')
end
