#!/usr/bin/sh


# touchpad="ELAN0501:00 04F3:3060 Touchpad"

# xinput set-prop "$touchpad" "libinput Tapping Enabled" 1
# xinput set-prop "$touchpad" "libinput Natural Scrolling Enabled" 1
# xinput set-prop "$touchpad" "libinput Accel Speed" 0.2
#xinput set-prop "$touchpad" "libinput Disable While Typing Enabled" 0

# xinput set-prop "ELAN0501:00 04F3:3060 Mouse" "libinput Accel Speed" -0.5

# setxkbmap -layout us,ru -option grp:shifts_toggle -option ctrl:nocaps
