[default]
depends = ["wayland", "scripts", "alacritty", "kitty", "dircolors", "emacs", "wallpapers", "flameshot", "bash", "fish", "git"]

[wallpapers.files]
wallpapers = { target = "~/pics/wallpapers", type = "symbolic" }

[systemd.files]
systemd = "~/.config/systemd/user"

[backup.files]
kopiaignore = { target = "~/.kopiaignore", type = "template" }

[scripts.files]
scripts = { target = "~/scripts", type = "template" }

[firejail.files]
firejail = "~/.config/firejail"

[alacritty.files]
alacritty = "~/.config/alacritty"

[kitty.files]
"kitty.conf" = { target = "~/.config/kitty/kitty.conf", type = "symbolic" }

[git.files]
gitconfig = "~/.gitconfig"

[dircolors.files]
dircolors = "~/.dircolors"

[bash.files]
"bashrc" = "~/.bashrc"

[fish.files]
fish = "~/.config/fish"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[emacs.files]
doom = "~/.doom.d"

[flameshot.files]
"flameshot.ini" = { target = "~/.config/flameshot/flameshot.ini", type = "symbolic" }

[i3status.files]
"i3status-rust.toml" = "~/.config/i3status-rust/config.toml"

[xinit.files]
xinit = "~/.xinitrc"

[i3.files]
i3 = "~/.config/i3"

[picom.files]
"picom.conf" = "~/.config/picom/picom.conf"

[chromium.files]
"chromium-flags" = "~/.config/chromium-flags.conf"

[compfy.files]
"compfy.conf" = "~/.config/compfy/compfy.conf"

[dunst.files]
"dunstrc" = "~/.config/dunst/dunstrc"

[nu.files]
nushell = "~/.config/nushell"

[wayland.files]
hypr = "~/.config/hypr"
"hyprland-portals.conf" = "~/.config/xdg-desktop-portal/hyprland-portals.conf"
"hypr/wlinitrc" = "~/.local/bin/wlinitrc"
waybar = { target = "~/.config/waybar", type = "symbolic" }
wofi = "~/.config/wofi"
